name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and test, Rust-stable
    strategy:
      matrix:
        toolchain:
          - stable
    runs-on: ubuntu-latest
    steps:
      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          override: true

      # Build and test.
      - run: cargo +${{matrix.toolchain}} build
      - run: cargo +${{matrix.toolchain}} test
      - run: cargo +${{matrix.toolchain}} bench --no-run

  build:
    name: Build, MSRV
    strategy:
      matrix:
        toolchain:
          - "1.65"
    runs-on: ubuntu-latest
    steps:
      # Get a checkout and rust toolchain.
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          override: true

      # Build.
      - run: cargo +${{matrix.toolchain}} build
